theme: jekyll-theme-slate
url: https://pwsiegel.github.io
title: Random Patterns
description: A blog by Paul Siegel
show_downloads: false
markdown: kramdown
kramdown:
    parse_block_html: true
plugins:
    - jemoji
